### ISSUE TITLE
Handle invalid/non logical dates

### ISSUE THREAD

**Issue by deeaitsch84** [klammbueddel/txt2jira#3]
### Expected behaviour
If a date is not valid, the application should deny the export to JIRA

### Actual behaviour
The application will generate a randomized(?) date and allow the export

### Steps to reproduce

1. Use 00.10.2022 as date header in log file
2. Commit the changes

**Comment by klammbueddel** [comment]
Hi @deeaitsch84,

The `00.10.2022` will be interpreted as `30.09.2022`. This is default PHP behaviour and I think I am not going to work around this.

**Comment by deeaitsch84** [comment]
Hi,

thats true, but a validation is quite easy and would be a quick win while preventing erroneous user input

```
function validateDate($date, $format = 'Y-m-d'){
    $d = DateTime::createFromFormat($format, $date);
    return $d && $d->format($format) === $date;
}
```

Dennis

**Comment by klammbueddel** [comment]
Hi Dennis,
thank you, I added the validation. Logs with invalid dates are ignored by now.
